---
version: 1

container_globals:
  skip_push: true

container:
- name: app
  Dockerfile: Dockerfile
  registry: quay.io/rafecolton
  project: docker-builder
  tags:
  - latest
  - "{{ sha }}"
  - "{{ tag }}"
  - "{{ branch }}"

# vim:ft=yaml
