version = 1

[[container]]
name = "app"
Dockerfile = "Dockerfile"
registry = "quay.io/rafecolton"
project = "docker-builder"
tags = ["latest", "{{ sha }}", "{{ tag }}", "{{ branch }}"]
skip_push = true

# vim:ft=toml
