language: go
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
go:
- 1.8.3
- tip
script:
- make test
after_success:
- make goveralls
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
    - secure: BWl5TwdzJjgFDV29DvZtmNDwzhEuLx4QxVwgwVjrJmgL1jjzfXfg/AabUEeUq7GsF/2OJbpZjKI1F0DSaMG70BjZqhljiRjplSJZXL49APZ7xd9gTS+xuAfILf4soihMKWbnDUh/5wNMSwCDABhbukiMyIPONYcCTxigbypdZCs=
    - GO15VENDOREXPERIMENT=1
